### PR TITLE
feat: provide browser-ready bundle (requires zod import-map)

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

**Comment by brettz9** [comment]
The `--legacy-output` option seems to be the one way it won't overwrite our existing `dist/index.js` file (overwriting it may be ok as far as Node, but wouldn't think so for TypeScript which writes to different files).

**Comment by Gregoor** [comment]
Let's give it a shot!

**Comment by brettz9** [comment]
Looks like there was a publish error: https://github.com/commonbaseapp/zodex/actions/runs/11071258234/job/30762829124

**Comment by brettz9** [comment]
The error is indicating you've already published "0.0.0-dev". Did you mean to set up semantic-release?

**Comment by Gregoor** [comment]
Hm yeah maybe, it was working before, it's not clear to me from the log what might have broken

**Comment by brettz9** [comment]
Shall I file an issue with https://github.com/go-semantic-release/action ?

**Comment by Gregoor** [comment]
I think we should be able to figure this out, it ran just fine before merging this PR:

So I guess we just need to figure out: what changed OR what isn't deterministic about our CI

**Comment by brettz9** [comment]
The changes though would need to look back, I think, to the last version, and there have been a number of changes, including the workspace changes, since that version was published: https://github.com/commonbaseapp/zodex/compare/v0.18.2...v0.19.0 .

**Comment by Gregoor** [comment]
true, you're right, I looked at the wrong thing!

**Comment by brettz9** [comment]
Don't know how well this applies, but per https://github.com/go-semantic-release/semantic-release/issues/77 , there is no support for monorepos in go-semantic-release. 

This comes up as a top Google search result: https://github.com/pmowrer/semantic-release-monorepo and has instructions for pnpm.

**Comment by Gregoor** [comment]
Uuh yeah dang, that makes a lot of sense, I didn't think about those implications, thank you for doing that for me. I'll do some thinking from here how to resolve it!

**Comment by Gregoor** [comment]
I fear I won't be finding the time for it in the next while, sorry!

**Pull request merged**
