### PR TITLE
feat: deserialisation and restructuring

### PR DESCRIPTION
**Pull request by Gregoor**
Added deserialization and restructured the project into a monorepo*.

@brettz9 I've attempt to port all your additions over, I hope non got lost in the merging frenzy.

*that's also the remaining TODO: Will have to adjust release infra to use https://github.com/pmowrer/semantic-release-monorepo to enable per-package publishing.

### CODE REVIEW

**Comment by brettz9** [comment]
Ok. Any ETA on the completion of this PR?

**Comment by Gregoor** [comment]
I'm currently running on an error, which should be gone once https://github.com/pmowrer/semantic-release-monorepo/pull/137 is merged.

That said, to unblock, I could also delay the multi-package setup and get the deserialization part already merged. Let me sleep on it, I'll make a call tomorrow.

**Comment by Gregoor** [comment]
@brettz9 took a bit longer to sleep on it. I'm pretty busy with other project, so I'll let this PR lie dormant and would be fine with reviewing and eventually merging whatever you have lined up!

**Comment by brettz9** [comment]
Hi @Gregoor ... Hope all is going well...

Any expectations of being able to revisit this PR? It looks like per https://github.com/pmowrer/semantic-release-monorepo/pull/137#issuecomment-1789384929 , that there is another option for the semantic release tool?

**Comment by Gregoor** [comment]
Hi @brettz9, thanks I'm good, hope you too!

That PR looks interesting, Unfortunately I was not able to get a typed version of (de)serialisation to work, TypeScript is just too much of an unwieldy beast when it comes to recursive types. A better path forward would probably be stripping the type mapping and just shipping the PR without it.

I'm also not working on commonbase anymore and don't have use case for zodex myself atm, happy to review a PR that does that though.

**Comment by brettz9** [comment]
If I do get to a PR, you'd be ok without the monorepo changes--just the addition of the deserialize file in JavaScript form (or possibly TypeScript with some `any` types where needed to get things to work)?

**Comment by Gregoor** [comment]
I'd be fine without the monorepo changes, though it should be workable without anys, I'd hope. I'm happy to review it, though I don't have merge rights.

**Comment by brettz9** [comment]
Sorry, it seems it is well above my current TS skills, so short of stripping the types, I don't think I can manage a PR. :-(

**Comment by brettz9** [comment]
Perhaps this can be closed now, too...

**Pull request closed without merging**
