### PR TITLE
Browser

### PR DESCRIPTION
**Pull request by brettz9**
feat: add esm build

Also:
- docs: adds browser demo

### CODE REVIEW

**Comment by Gregoor** [comment]
While I like the simplicity of having browser ready JS, I don't like vendoring in zod. My leaning would be to just use vite, as we're already depending on it anyway

**Comment by brettz9** [comment]
I've added #37 . If that meets your needs, I can rebase the other PRs fairly easily on top of it.

**Comment by Gregoor** [comment]
Uuh I must’ve missed the gh pages part sorry, will check again (looking at it from my phone atm, so it will be later).
But in general I’d also use vite to do a static GitHub pages export

**Comment by brettz9** [comment]
Re: GitHub Pages, there's no special code for it--just by bundling it in `vendor`, the `main` branch could be configured on GitHub to run the app.

But with your preference for Vite, though I've gotten things going with local use of vite in #37, if you wouldn't mind, I'll leave any production deployment work to you, as the production configuration looks a little involved, and you might have your own ideas about how to do it anyways.

**Comment by Gregoor** [comment]
Happy to take prod deployment over, but it's gonna be a week or so until I have time to look into it

**Comment by brettz9** [comment]
I've amended this PR to be on top of a commit which removes React. I can amend to add back React if desired, but it sounded like that was the way you may be going.

**Comment by brettz9** [comment]
Woohoo! Down to the last PR (assuming you want to remove React which this one has a commit for), though I know as it requires your intervention to get it deployed to production, it may take time for you to get to it. Should be great to have a browser build merged, and I can perhaps finally leave you with some peace. :-)

**Comment by brettz9** [comment]
I dropped the removal of `infer.ts` from this PR (though I'll leave it to you on exporting it).

**Comment by brettz9** [comment]
Closed in favor of #46

**Pull request closed without merging**
